### ISSUE TITLE
[FR] locality bonus: locations closer to the cursor should be "easier" to jump to

### ISSUE THREAD

**Issue by PavelDvorak** [DavidLGoldberg/jumpy2#18]
**thanks for the extension!**
if possible, locations closer to the cursor should be "easier" to jump to, sort of implementing a locality bonus.

By "easier" I mean, for example: 
1) jump to close locations via one letter jumps, and only in the range "asdfghjkl"
2) jump to close locations via two letter jumps, and only in the range "asdfghjkl"

Locations farther away may use the rest of the alphabet, and also combination of lowercase/upperase letters, as is the case today.

**Comment by DavidLGoldberg** [comment]
Few thoughts:

- I don't think that locality is highly correlated _enough_ with where a user wants to jump to add the increased complexity.
- There are more complex systems out there like vim motion or easy motion which promote fewer clicks in the ideal case, but you often have to "wait" (until more keys are pressed) for the worst case.  Jumpy is more of an equal distribution and you only have to 1. activate 2. jump.  So, always 2 "quick" (ish) steps.
- Whenever you use let's say, home row keys only (1 char length), you cut down on the # of labels that can be generated to a degree as well, since now labels can't start with ~ 1/3 of the keys.  Unless you do fancier things like quick follow-up jumps or something complex.
- I think if someone is using Jumpy they should probably also invest in hyper/meta key arrow movement for small quick adjustments, vim bindings, or emacs derived (usually I think?) built-in moves (ie. standard vs code).
- I was trying to avoid mouse movements, not all previously acceptable keyboard jumps.  Although, I do have some plans to make more jump points...which might up the frequency of jumps overall.

I'm going to close the issue for now, but thanks so much for the feedback.  Keep the ideas flowing! 🙏

**Comment by PavelDvorak** [comment]
No problem thanks for the quick reply 👍🏻
